apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: springbootdockerexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdockerexample
  template:
    metadata:
      labels:
        app: springbootdockerexample
    spec:
      containers:
      - name: jenkins
        image: naresh240/springbootdockerexample
        ports:
        - containerPort: 8080
   
---     
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springbootdockerexample
  name: springbootdockerexample
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    name: springbootdockerexample
