apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: naresh240/springbootdockerexample
        name: springboot
        ports:
        - name: springboot
          containerPort: 8081
   
---     
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    name: springboot